export const FETCH_CHARACTERS_ERROR = "FETCH_CHARACTERS_ERROR"
export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START"
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS'


export const FETCH_LOCATIONS_ERROR = "FETCH_LOCATIONS_ERROR"
export const FETCH_LOCATIONS_START = "FETCH_LOCATIONS_START"
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'

